//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPOS.Dash.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCT_DS_WIPOHague
    {
        public System.Guid Id { get; set; }
        public string GroupType { get; set; }
        public System.DateTime ReportingDate { get; set; }
        public int IntlRegistrations { get; set; }
        public int DesignsIntlRegistrations { get; set; }
        public int IntlApplications { get; set; }
        public int DesignsIntlApplications { get; set; }
        public int Renewals { get; set; }
        public int DesignsRenewals { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
